spring:
  mail:
    host: smtp.gmail.com
    username: 1hanho94@gmail.com
    password: yurrwwwvnufdsfhb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  servlet:
    multipart:
      location: /Users/han/temp
      max-request-size: 30MB
  redis:
    port: 6379
    host: localhost
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/mini
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: local
logging.level:
  org.hibernate.SQL: debug

file-dir : /Users/han/attach/

---
spring:
  servlet:
    multipart:
      location: /upload/temp
  datasource:
    url: jdbc:h2:~/mini
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: pro
  redis:
    port: 6379
    host: localhost
logging.level:
  org.hibernate.SQL: error

file.dir : /attach